### ISSUE TITLE
 Adding stripe checkout for automating transactions 

### ISSUE THREAD

**Issue by rajlaxmi03** [open-xyz/build-fast#8]
Adding stripe checkout for automating transactions

**Comment by Ansh101112** [comment]
I want to work on this issue kindly assign me this issue @rohansx @rajlaxmi03

**Comment by rohansx** [comment]
@rajlaxmi03 since it will be an open source boiler plate.. there is no need of payment gateway.
Appreciate your suggestion, but you can take on different issue
